# Generated by Django 3.2.9 on 2021-11-16 21:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                (
                    "description",
                    models.TextField(
                        validators=[django.core.validators.MaxLengthValidator(10000)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO DO", "TO DO"),
                            ("IN PROGRESS", "IN PROGRESS"),
                            ("REVIEW", "REVIEW"),
                            ("DONE", "DONE_"),
                        ],
                        max_length=32,
                    ),
                ),
                ("due_date", models.DateTimeField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("edited_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="created_task_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "member",
                    models.OneToOneField(
                        blank=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task",
                        to="projects.project",
                    ),
                ),
            ],
        ),
    ]
